### ISSUE TITLE
Uncaught QgsCsException: forward transform of
(1660.630671, -243.935622)
PROJ.4:  +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 +to  +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs
Error: latitude or longitude exceeded limits


### ISSUE THREAD

**Issue by rihorn** [sourcepole/qgis-openlayers-plugin#34]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/ian.horn/.qgis2/python/plugins\openlayers_plugin\weblayers\weblayer.py", line 100, in addLayer
    self._addLayerCallback(self)
  File "C:/Users/ian.horn/.qgis2/python/plugins\openlayers_plugin\openlayers_plugin.py", line 179, in addLayer
    self.setMapCrs(coordRefSys)
  File "C:/Users/ian.horn/.qgis2/python/plugins\openlayers_plugin\openlayers_plugin.py", line 227, in setMapCrs
    extMap = coordTrans.transform(extMap, QgsCoordinateTransform.ForwardTransform)
QgsCsException: forward transform of
(1660.630671, -243.935622)
PROJ.4:  +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 +to  +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs
Error: latitude or longitude exceeded limits

```
openlayers_plugin 1.4.3, QGIS 2.18.11 on Windows 7

**Comment by HusseinKabbout** [comment]
This issue will be closed, because the qgis2 version of this plugin is not maintained anymore.
