### ISSUE TITLE
UnicodeEncodeError if proxy credentials contain non-ascii characters

### ISSUE THREAD

**Issue by borysiasty** [sourcepole/qgis-openlayers-plugin#38]
Here is an exception on plugin loading:

```
Traceback (most recent call last):
  File "/home/borysjessie/sources/qgis/build-2_18/output/python/qgis/utils.py", line 342, in startPlugin
    plugins[packageName].initGui()
  File "/home/borysjessie/.qgis2/python/plugins/openlayers_plugin/openlayers_plugin.py", line 153, in initGui
    self.setGDALProxy()
  File "/home/borysjessie/.qgis2/python/plugins/openlayers_plugin/openlayers_plugin.py", line 328, in setGDALProxy
    os.environ["GDAL_HTTP_PROXYUSERPWD"] = gdalHttpProxyuserpwd
  File "/usr/lib/python2.7/os.py", line 473, in __setitem__
    putenv(key, item)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u015a' in position 4: ordinal not in range(128)
```

**Comment by pka** [comment]
Fixed in v1.4.8
