### ISSUE TITLE
I tried to install fro zip: downloaded entire repo as a zip file, but qgis threw an error. plz help!

### ISSUE THREAD

**Issue by annanurov** [sourcepole/qgis-openlayers-plugin#68]

**Comment by annanurov** [comment]
QGIS versio 3.4.14
This is the error message:
An error occurred during execution of following code:
pyplugin_installer.instance().installFromZipFile(r'C:\Users\water\Downloads\qgis-openlayers-plugin-master.zip')


Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
AttributeError: module 'qgis-openlayers-plugin-master' has no attribute 'classFactory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "", line 1, in 
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\pyplugin_installer\installer.py", line 612, in installFromZipFile
    if startPlugin(pluginName):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 337, in startPlugin
    _unloadPluginModules(packageName)
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 404, in _unloadPluginModules
    mods = _plugin_modules[packageName]
KeyError: 'qgis-openlayers-plugin-master'


Python version:
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

QGIS version:
3.4.14-Madeira 'Madeira', c92881c294

Python path:
['C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python', 'C:/Users/water/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:/Users/water/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins', 'C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins', 'C:\\PROGRA~1\\QGIS3~1.4\\apps\\gdal2\\pymod3\\lib\\site-packages', 'C:\\Users\\water\\Documents', 'C:\\Program Files\\QGIS 3.4\\bin\\python37.zip', 'C:\\PROGRA~1\\QGIS3~1.4\\apps\\Python37\\DLLs', 'C:\\PROGRA~1\\QGIS3~1.4\\apps\\Python37\\lib', 'C:\\Program Files\\QGIS 3.4\\bin', 'C:\\PROGRA~1\\QGIS3~1.4\\apps\\Python37', 'C:\\PROGRA~1\\QGIS3~1.4\\apps\\Python37\\lib\\site-packages', 'C:\\PROGRA~1\\QGIS3~1.4\\apps\\Python37\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGIS3~1.4\\apps\\Python37\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGIS3~1.4\\apps\\Python37\\lib\\site-packages\\Pythonwin', 'C:/Users/water/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:/Users/water/Documents/GIS DataBase/qgis_sample_data/projects']
