### ISSUE TITLE
Qgis throwing import error while installing the plugin

### ISSUE THREAD

**Issue by mm5m** [sourcepole/qgis-openlayers-plugin#73]
Other plugins are being installed without any issue.
plz see the log below.

> Couldn't load plugin 'openlayers_plugin' due to an error when calling its classFactory() method 
> 
> ImportError: cannot import name 'OpenlayersPlugin' from 'openlayers_plugin' (C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\openlayers_plugin\__init__.py) 
> Traceback (most recent call last):
>   File "C:\PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
>     plugins[packageName] = package.classFactory(iface)
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\openlayers_plugin\__init__.py", line 25, in classFactory
>     from openlayers_plugin import OpenlayersPlugin
> ImportError: cannot import name 'OpenlayersPlugin' from 'openlayers_plugin' (C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\openlayers_plugin\__init__.py)
> 
> 
> Python version: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
> QGIS version: 3.34.6-Prizren Prizren, 623828f5 
> 
> Python Path:
> C:/PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python
> C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
> C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
> C:/PROGRA~1/QGIS33~1.6/apps/qgis-ltr/./python/plugins
> C:\PROGRA~1\QGIS33~1.6\apps\grass\grass83\etc\python
> C:\Users\Admin\Documents
> C:\Program Files\QGIS 3.34.6\bin\python312.zip
> C:\PROGRA~1\QGIS33~1.6\apps\Python312\DLLs
> C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib
> C:\Program Files\QGIS 3.34.6\bin
> C:\PROGRA~1\QGIS33~1.6\apps\Python312
> C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages
> C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages\win32
> C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages\win32\lib
> C:\PROGRA~1\QGIS33~1.6\apps\Python312\Lib\site-packages\Pythonwin
> C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
> D:/Projects/QgisProjects

**Comment by degenoah** [comment]
It appears this plugin is no longer maintained and doesn't support QGIS 3, which is why.

**Comment by LouGit** [comment]
> and doesn't support QGIS 3

This is strange:

- the openlayers_plugin is working just fine, right now, on a GNU/Linux Devuan Stable machine with QGIS 3.38.3 Grenoble;

- but it doesn't run on another machine, a GNU/Linux Debian Sid machine with Version de QGIS 3.40.5-Bratislava.

I'll try to investigate a bit further on this issue.

**Comment by LouGit** [comment]
I found a workaround (dirty, but it *just works*).

In my current project where I want to add an OpenLayers map, I do:
1. menu "Layer",
1. menu "Embed Layers and groups..."
1. in the dialog box "Project file", click on the "..." button;
1. choose an (old) QGIS project file which already has some OpenLayers layers ;
1. select the layer(s) I wish;
1. click on "OK"...

And I get my embedded layers.

They appear with a "chain" icon on the right, in the "Layers" pane, which shows that these layers are "linked" to the other project, which may induce a dependency.  To avoid this, just:
1. right-click on each layer
2. choose "Duplicate Layer"

And then the copies of OpenLayers layers are "normal" layers, without the "chain" sign on the right.
